  
tasks:
  -init: npm install
   command: >
      npm i -g json-server &&
      json-server --watch db.json --port 3000
  -init: npm install
   command: >
     npm install 
    npm run dev 
    
