ports:
  - port: 3001
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
tasks:
  - init: yarn install
    command: yarn dev
  - command: yarn add json-server
vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
