ports:
  - port: 3001
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
tasks:
  - before: npm i
    init: npm i -g json-server
    command: json-server --watch db.json --port 3000 --no-cors
  - command: npm run dev
vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
